git:
  log:
    showGraph: "always"
    showWholeGraph: true
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never --side-by-side --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  diffRenderers:
    - colorArg: always
      command: delta --dark --paging=never --syntax-theme base16-256 -s
os:
  editPreset: 'nvim'
