[mgr]
linemode="mtime"

[opener]
editor = [
    { run="%EDITOR% %s", for="windows", desc="Edit", orphan=true },
    { run="$editor %s",  for="unix",    desc="Edit", orphan=true },
]
code = [
    { run="code %s", orphan=true, desc="Code" },
]
vim = [
    { run="vim %s", orphan=true, desc="Vim" },
]
explorer = [
    { run="explorer %s", orphan=true, for="windows" }
]

[open]
rules = [
    { url="*.lnk", for="windows", use="explorer" }
]
# vi:se et sw=4 ts=4 sts=4:
