-- tokyonight-night : folke/tokyonight.nvim v4.14.1 (cdc07ac) から生成した静的カラースキーム
-- https://github.com/folke/tokyonight.nvim (Apache License 2.0)
-- 手で編集しないこと。再生成手順は scripts/gen_tokyonight.lua を参照。

if vim.g.colors_name then
    vim.cmd('hi clear')
end
vim.o.background = 'dark'
vim.o.termguicolors = true
vim.g.colors_name = 'tokyonight-night'

local hl = vim.api.nvim_set_hl
hl(0, "@annotation", { link = "PreProc" })
hl(0, "@attribute", { link = "PreProc" })
hl(0, "@boolean", { link = "Boolean" })
hl(0, "@character", { link = "Character" })
hl(0, "@character.printf", { link = "SpecialChar" })
hl(0, "@character.special", { link = "SpecialChar" })
hl(0, "@comment", { link = "Comment" })
hl(0, "@comment.error", { fg = "#db4b4b" })
hl(0, "@comment.hint", { fg = "#1abc9c" })
hl(0, "@comment.info", { fg = "#0db9d7" })
hl(0, "@comment.note", { fg = "#1abc9c" })
hl(0, "@comment.todo", { fg = "#7aa2f7" })
hl(0, "@comment.warning", { fg = "#e0af68" })
hl(0, "@constant", { link = "Constant" })
hl(0, "@constant.builtin", { link = "Special" })
hl(0, "@constant.macro", { link = "Define" })
hl(0, "@constructor", { fg = "#bb9af7" })
hl(0, "@constructor.tsx", { fg = "#2ac3de" })
hl(0, "@diff.delta", { link = "DiffChange" })
hl(0, "@diff.minus", { link = "DiffDelete" })
hl(0, "@diff.plus", { link = "DiffAdd" })
hl(0, "@function", { link = "Function" })
hl(0, "@function.builtin", { link = "Special" })
hl(0, "@function.call", { link = "@function" })
hl(0, "@function.macro", { link = "Macro" })
hl(0, "@function.method", { link = "Function" })
hl(0, "@function.method.call", { link = "@function.method" })
hl(0, "@keyword", { fg = "#9d7cd8", italic = true })
hl(0, "@keyword.conditional", { link = "Conditional" })
hl(0, "@keyword.coroutine", { link = "@keyword" })
hl(0, "@keyword.debug", { link = "Debug" })
hl(0, "@keyword.directive", { link = "PreProc" })
hl(0, "@keyword.directive.define", { link = "Define" })
hl(0, "@keyword.exception", { link = "Exception" })
hl(0, "@keyword.function", { fg = "#bb9af7" })
hl(0, "@keyword.import", { link = "Include" })
hl(0, "@keyword.operator", { link = "@operator" })
hl(0, "@keyword.repeat", { link = "Repeat" })
hl(0, "@keyword.return", { link = "@keyword" })
hl(0, "@keyword.storage", { link = "StorageClass" })
hl(0, "@label", { fg = "#7aa2f7" })
hl(0, "@lsp.type.boolean", { link = "@boolean" })
hl(0, "@lsp.type.builtinType", { link = "@type.builtin" })
hl(0, "@lsp.type.comment", { link = "@comment" })
hl(0, "@lsp.type.decorator", { link = "@attribute" })
hl(0, "@lsp.type.deriveHelper", { link = "@attribute" })
hl(0, "@lsp.type.enum", { link = "@type" })
hl(0, "@lsp.type.enumMember", { link = "@constant" })
hl(0, "@lsp.type.escapeSequence", { link = "@string.escape" })
hl(0, "@lsp.type.formatSpecifier", { link = "@markup.list" })
hl(0, "@lsp.type.generic", { link = "@variable" })
hl(0, "@lsp.type.interface", { fg = "#57c5e5" })
hl(0, "@lsp.type.keyword", { link = "@keyword" })
hl(0, "@lsp.type.lifetime", { link = "@keyword.storage" })
hl(0, "@lsp.type.namespace", { link = "@module" })
hl(0, "@lsp.type.namespace.python", { link = "@variable" })
hl(0, "@lsp.type.number", { link = "@number" })
hl(0, "@lsp.type.operator", { link = "@operator" })
hl(0, "@lsp.type.parameter", { link = "@variable.parameter" })
hl(0, "@lsp.type.property", { link = "@property" })
hl(0, "@lsp.type.selfKeyword", { link = "@variable.builtin" })
hl(0, "@lsp.type.selfTypeKeyword", { link = "@variable.builtin" })
hl(0, "@lsp.type.string", { link = "@string" })
hl(0, "@lsp.type.typeAlias", { link = "@type.definition" })
hl(0, "@lsp.type.unresolvedReference", { sp = "#db4b4b", undercurl = true })
hl(0, "@lsp.type.variable", {})
hl(0, "@lsp.typemod.class.defaultLibrary", { link = "@type.builtin" })
hl(0, "@lsp.typemod.enum.defaultLibrary", { link = "@type.builtin" })
hl(0, "@lsp.typemod.enumMember.defaultLibrary", { link = "@constant.builtin" })
hl(0, "@lsp.typemod.function.defaultLibrary", { link = "@function.builtin" })
hl(0, "@lsp.typemod.keyword.async", { link = "@keyword.coroutine" })
hl(0, "@lsp.typemod.keyword.injected", { link = "@keyword" })
hl(0, "@lsp.typemod.macro.defaultLibrary", { link = "@function.builtin" })
hl(0, "@lsp.typemod.method.defaultLibrary", { link = "@function.builtin" })
hl(0, "@lsp.typemod.operator.injected", { link = "@operator" })
hl(0, "@lsp.typemod.string.injected", { link = "@string" })
hl(0, "@lsp.typemod.struct.defaultLibrary", { link = "@type.builtin" })
hl(0, "@lsp.typemod.type.defaultLibrary", { fg = "#27a1b9" })
hl(0, "@lsp.typemod.typeAlias.defaultLibrary", { fg = "#27a1b9" })
hl(0, "@lsp.typemod.variable.callable", { link = "@function" })
hl(0, "@lsp.typemod.variable.defaultLibrary", { link = "@variable.builtin" })
hl(0, "@lsp.typemod.variable.injected", { link = "@variable" })
hl(0, "@lsp.typemod.variable.static", { link = "@constant" })
hl(0, "@markup", { link = "@none" })
hl(0, "@markup.emphasis", { italic = true })
hl(0, "@markup.environment", { link = "Macro" })
hl(0, "@markup.environment.name", { link = "Type" })
hl(0, "@markup.heading", { link = "Title" })
hl(0, "@markup.heading.1.markdown", { bg = "#24293b", bold = true, fg = "#7aa2f7" })
hl(0, "@markup.heading.2.markdown", { bg = "#2e2a2d", bold = true, fg = "#e0af68" })
hl(0, "@markup.heading.3.markdown", { bg = "#272d2d", bold = true, fg = "#9ece6a" })
hl(0, "@markup.heading.4.markdown", { bg = "#1a2b32", bold = true, fg = "#1abc9c" })
hl(0, "@markup.heading.5.markdown", { bg = "#2a283b", bold = true, fg = "#bb9af7" })
hl(0, "@markup.heading.6.markdown", { bg = "#272538", bold = true, fg = "#9d7cd8" })
hl(0, "@markup.heading.7.markdown", { bg = "#31282c", bold = true, fg = "#ff9e64" })
hl(0, "@markup.heading.8.markdown", { bg = "#302430", bold = true, fg = "#f7768e" })
hl(0, "@markup.italic", { italic = true })
hl(0, "@markup.link", { fg = "#1abc9c" })
hl(0, "@markup.link.label", { link = "SpecialChar" })
hl(0, "@markup.link.label.symbol", { link = "Identifier" })
hl(0, "@markup.link.url", { link = "Underlined" })
hl(0, "@markup.list", { fg = "#89ddff" })
hl(0, "@markup.list.checked", { fg = "#73daca" })
hl(0, "@markup.list.markdown", { bold = true, fg = "#ff9e64" })
hl(0, "@markup.list.unchecked", { fg = "#7aa2f7" })
hl(0, "@markup.math", { link = "Special" })
hl(0, "@markup.raw", { link = "String" })
hl(0, "@markup.raw.markdown_inline", { bg = "#414868", fg = "#7aa2f7" })
hl(0, "@markup.strikethrough", { strikethrough = true })
hl(0, "@markup.strong", { bold = true })
hl(0, "@markup.underline", { underline = true })
hl(0, "@module", { link = "Include" })
hl(0, "@module.builtin", { fg = "#f7768e" })
hl(0, "@namespace.builtin", { link = "@variable.builtin" })
hl(0, "@none", {})
hl(0, "@number", { link = "Number" })
hl(0, "@number.float", { link = "Float" })
hl(0, "@operator", { fg = "#89ddff" })
hl(0, "@property", { fg = "#73daca" })
hl(0, "@punctuation.bracket", { fg = "#a9b1d6" })
hl(0, "@punctuation.delimiter", { fg = "#89ddff" })
hl(0, "@punctuation.special", { fg = "#89ddff" })
hl(0, "@punctuation.special.markdown", { fg = "#ff9e64" })
hl(0, "@string", { link = "String" })
hl(0, "@string.documentation", { fg = "#e0af68" })
hl(0, "@string.escape", { fg = "#bb9af7" })
hl(0, "@string.regexp", { fg = "#b4f9f8" })
hl(0, "@tag", { link = "Label" })
hl(0, "@tag.attribute", { link = "@property" })
hl(0, "@tag.delimiter", { link = "Delimiter" })
hl(0, "@tag.delimiter.tsx", { fg = "#5d7ab8" })
hl(0, "@tag.javascript", { fg = "#f7768e" })
hl(0, "@tag.tsx", { fg = "#f7768e" })
hl(0, "@type", { link = "Type" })
hl(0, "@type.builtin", { fg = "#27a1b9" })
hl(0, "@type.definition", { link = "Typedef" })
hl(0, "@type.qualifier", { link = "@keyword" })
hl(0, "@variable", { fg = "#c0caf5" })
hl(0, "@variable.builtin", { fg = "#f7768e" })
hl(0, "@variable.member", { fg = "#73daca" })
hl(0, "@variable.parameter", { fg = "#e0af68" })
hl(0, "@variable.parameter.builtin", { fg = "#dab484" })
hl(0, "ALEErrorSign", { fg = "#db4b4b" })
hl(0, "ALEWarningSign", { fg = "#e0af68" })
hl(0, "AerialArrayIcon", { link = "LspKindArray" })
hl(0, "AerialBooleanIcon", { link = "LspKindBoolean" })
hl(0, "AerialClassIcon", { link = "LspKindClass" })
hl(0, "AerialColorIcon", { link = "LspKindColor" })
hl(0, "AerialConstantIcon", { link = "LspKindConstant" })
hl(0, "AerialConstructorIcon", { link = "LspKindConstructor" })
hl(0, "AerialEnumIcon", { link = "LspKindEnum" })
hl(0, "AerialEnumMemberIcon", { link = "LspKindEnumMember" })
hl(0, "AerialEventIcon", { link = "LspKindEvent" })
hl(0, "AerialFieldIcon", { link = "LspKindField" })
hl(0, "AerialFileIcon", { link = "LspKindFile" })
hl(0, "AerialFolderIcon", { link = "LspKindFolder" })
hl(0, "AerialFunctionIcon", { link = "LspKindFunction" })
hl(0, "AerialGuide", { fg = "#3b4261" })
hl(0, "AerialInterfaceIcon", { link = "LspKindInterface" })
hl(0, "AerialKeyIcon", { link = "LspKindKey" })
hl(0, "AerialKeywordIcon", { link = "LspKindKeyword" })
hl(0, "AerialLine", { link = "LspInlayHint" })
hl(0, "AerialMethodIcon", { link = "LspKindMethod" })
hl(0, "AerialModuleIcon", { link = "LspKindModule" })
hl(0, "AerialNamespaceIcon", { link = "LspKindNamespace" })
hl(0, "AerialNormal", { bg = "NONE", fg = "#c0caf5" })
hl(0, "AerialNullIcon", { link = "LspKindNull" })
hl(0, "AerialNumberIcon", { link = "LspKindNumber" })
hl(0, "AerialObjectIcon", { link = "LspKindObject" })
hl(0, "AerialOperatorIcon", { link = "LspKindOperator" })
hl(0, "AerialPackageIcon", { link = "LspKindPackage" })
hl(0, "AerialPropertyIcon", { link = "LspKindProperty" })
hl(0, "AerialReferenceIcon", { link = "LspKindReference" })
hl(0, "AerialSnippetIcon", { link = "LspKindSnippet" })
hl(0, "AerialStringIcon", { link = "LspKindString" })
hl(0, "AerialStructIcon", { link = "LspKindStruct" })
hl(0, "AerialTextIcon", { link = "LspKindText" })
hl(0, "AerialTypeParameterIcon", { link = "LspKindTypeParameter" })
hl(0, "AerialUnitIcon", { link = "LspKindUnit" })
hl(0, "AerialValueIcon", { link = "LspKindValue" })
hl(0, "AerialVariableIcon", { link = "LspKindVariable" })
hl(0, "AlphaButtons", { fg = "#7dcfff" })
hl(0, "AlphaFooter", { fg = "#2ac3de" })
hl(0, "AlphaHeader", { fg = "#7aa2f7" })
hl(0, "AlphaHeaderLabel", { fg = "#ff9e64" })
hl(0, "AlphaShortcut", { fg = "#ff9e64" })
hl(0, "BlinkCmpDoc", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "BlinkCmpDocBorder", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "BlinkCmpGhostText", { fg = "#414868" })
hl(0, "BlinkCmpKindArray", { link = "LspKindArray" })
hl(0, "BlinkCmpKindBoolean", { link = "LspKindBoolean" })
hl(0, "BlinkCmpKindClass", { link = "LspKindClass" })
hl(0, "BlinkCmpKindCodeium", { bg = "NONE", fg = "#1abc9c" })
hl(0, "BlinkCmpKindColor", { link = "LspKindColor" })
hl(0, "BlinkCmpKindConstant", { link = "LspKindConstant" })
hl(0, "BlinkCmpKindConstructor", { link = "LspKindConstructor" })
hl(0, "BlinkCmpKindCopilot", { bg = "NONE", fg = "#1abc9c" })
hl(0, "BlinkCmpKindDefault", { bg = "NONE", fg = "#a9b1d6" })
hl(0, "BlinkCmpKindEnum", { link = "LspKindEnum" })
hl(0, "BlinkCmpKindEnumMember", { link = "LspKindEnumMember" })
hl(0, "BlinkCmpKindEvent", { link = "LspKindEvent" })
hl(0, "BlinkCmpKindField", { link = "LspKindField" })
hl(0, "BlinkCmpKindFile", { link = "LspKindFile" })
hl(0, "BlinkCmpKindFolder", { link = "LspKindFolder" })
hl(0, "BlinkCmpKindFunction", { link = "LspKindFunction" })
hl(0, "BlinkCmpKindInterface", { link = "LspKindInterface" })
hl(0, "BlinkCmpKindKey", { link = "LspKindKey" })
hl(0, "BlinkCmpKindKeyword", { link = "LspKindKeyword" })
hl(0, "BlinkCmpKindMethod", { link = "LspKindMethod" })
hl(0, "BlinkCmpKindModule", { link = "LspKindModule" })
hl(0, "BlinkCmpKindNamespace", { link = "LspKindNamespace" })
hl(0, "BlinkCmpKindNull", { link = "LspKindNull" })
hl(0, "BlinkCmpKindNumber", { link = "LspKindNumber" })
hl(0, "BlinkCmpKindObject", { link = "LspKindObject" })
hl(0, "BlinkCmpKindOperator", { link = "LspKindOperator" })
hl(0, "BlinkCmpKindPackage", { link = "LspKindPackage" })
hl(0, "BlinkCmpKindProperty", { link = "LspKindProperty" })
hl(0, "BlinkCmpKindReference", { link = "LspKindReference" })
hl(0, "BlinkCmpKindSnippet", { link = "LspKindSnippet" })
hl(0, "BlinkCmpKindString", { link = "LspKindString" })
hl(0, "BlinkCmpKindStruct", { link = "LspKindStruct" })
hl(0, "BlinkCmpKindSupermaven", { bg = "NONE", fg = "#1abc9c" })
hl(0, "BlinkCmpKindTabNine", { bg = "NONE", fg = "#1abc9c" })
hl(0, "BlinkCmpKindText", { link = "LspKindText" })
hl(0, "BlinkCmpKindTypeParameter", { link = "LspKindTypeParameter" })
hl(0, "BlinkCmpKindUnit", { link = "LspKindUnit" })
hl(0, "BlinkCmpKindValue", { link = "LspKindValue" })
hl(0, "BlinkCmpKindVariable", { link = "LspKindVariable" })
hl(0, "BlinkCmpLabel", { bg = "NONE", fg = "#c0caf5" })
hl(0, "BlinkCmpLabelDeprecated", { bg = "NONE", fg = "#3b4261", strikethrough = true })
hl(0, "BlinkCmpLabelMatch", { bg = "NONE", fg = "#2ac3de" })
hl(0, "BlinkCmpMenu", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "BlinkCmpMenuBorder", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "BlinkCmpSignatureHelp", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "BlinkCmpSignatureHelpBorder", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "Bold", { bold = true, fg = "#c0caf5" })
hl(0, "BufferAlternate", { bg = "#3b4261", fg = "#c0caf5" })
hl(0, "BufferAlternateADDED", { bg = "#3b4261", fg = "#449dab" })
hl(0, "BufferAlternateCHANGED", { bg = "#3b4261", fg = "#6183bb" })
hl(0, "BufferAlternateDELETED", { bg = "#3b4261", fg = "#914c54" })
hl(0, "BufferAlternateERROR", { bg = "#3b4261", fg = "#db4b4b" })
hl(0, "BufferAlternateHINT", { bg = "#3b4261", fg = "#1abc9c" })
hl(0, "BufferAlternateINFO", { bg = "#3b4261", fg = "#0db9d7" })
hl(0, "BufferAlternateIndex", { bg = "#3b4261", fg = "#0db9d7" })
hl(0, "BufferAlternateMod", { bg = "#3b4261", fg = "#e0af68" })
hl(0, "BufferAlternateSign", { bg = "#3b4261", fg = "#0db9d7" })
hl(0, "BufferAlternateTarget", { bg = "#3b4261", fg = "#f7768e" })
hl(0, "BufferAlternateWARN", { bg = "#3b4261", fg = "#e0af68" })
hl(0, "BufferCurrent", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "BufferCurrentADDED", { bg = "#1a1b26", fg = "#449dab" })
hl(0, "BufferCurrentCHANGED", { bg = "#1a1b26", fg = "#6183bb" })
hl(0, "BufferCurrentDELETED", { bg = "#1a1b26", fg = "#914c54" })
hl(0, "BufferCurrentERROR", { bg = "#1a1b26", fg = "#db4b4b" })
hl(0, "BufferCurrentHINT", { bg = "#1a1b26", fg = "#1abc9c" })
hl(0, "BufferCurrentINFO", { bg = "#1a1b26", fg = "#0db9d7" })
hl(0, "BufferCurrentIndex", { bg = "#1a1b26", fg = "#0db9d7" })
hl(0, "BufferCurrentMod", { bg = "#1a1b26", fg = "#e0af68" })
hl(0, "BufferCurrentSign", { bg = "#1a1b26", fg = "#1a1b26" })
hl(0, "BufferCurrentTarget", { bg = "#1a1b26", fg = "#f7768e" })
hl(0, "BufferCurrentWARN", { bg = "#1a1b26", fg = "#e0af68" })
hl(0, "BufferInactive", { bg = "#202331", fg = "#616789" })
hl(0, "BufferInactiveADDED", { bg = "#202331", fg = "#3c8390" })
hl(0, "BufferInactiveCHANGED", { bg = "#202331", fg = "#536e9d" })
hl(0, "BufferInactiveDELETED", { bg = "#202331", fg = "#79424b" })
hl(0, "BufferInactiveERROR", { bg = "#202331", fg = "#b44144" })
hl(0, "BufferInactiveHINT", { bg = "#202331", fg = "#1a9c84" })
hl(0, "BufferInactiveINFO", { bg = "#202331", fg = "#1099b4" })
hl(0, "BufferInactiveIndex", { bg = "#202331", fg = "#737aa2" })
hl(0, "BufferInactiveMod", { bg = "#202331", fg = "#b8915b" })
hl(0, "BufferInactiveSign", { bg = "#202331", fg = "#1a1b26" })
hl(0, "BufferInactiveTarget", { bg = "#202331", fg = "#f7768e" })
hl(0, "BufferInactiveWARN", { bg = "#202331", fg = "#b8915b" })
hl(0, "BufferLineIndicatorSelected", { fg = "#6183bb" })
hl(0, "BufferOffset", { bg = "#16161e", fg = "#737aa2" })
hl(0, "BufferTabpageFill", { bg = "#262a3c", fg = "#737aa2" })
hl(0, "BufferTabpages", { bg = "#16161e", fg = "NONE" })
hl(0, "BufferVisible", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "BufferVisibleADDED", { bg = "#16161e", fg = "#449dab" })
hl(0, "BufferVisibleCHANGED", { bg = "#16161e", fg = "#6183bb" })
hl(0, "BufferVisibleDELETED", { bg = "#16161e", fg = "#914c54" })
hl(0, "BufferVisibleERROR", { bg = "#16161e", fg = "#db4b4b" })
hl(0, "BufferVisibleHINT", { bg = "#16161e", fg = "#1abc9c" })
hl(0, "BufferVisibleINFO", { bg = "#16161e", fg = "#0db9d7" })
hl(0, "BufferVisibleIndex", { bg = "#16161e", fg = "#0db9d7" })
hl(0, "BufferVisibleMod", { bg = "#16161e", fg = "#e0af68" })
hl(0, "BufferVisibleSign", { bg = "#16161e", fg = "#0db9d7" })
hl(0, "BufferVisibleTarget", { bg = "#16161e", fg = "#f7768e" })
hl(0, "BufferVisibleWARN", { bg = "#16161e", fg = "#e0af68" })
hl(0, "Character", { fg = "#9ece6a" })
hl(0, "CmpDocumentation", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "CmpDocumentationBorder", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "CmpGhostText", { fg = "#414868" })
hl(0, "CmpItemAbbr", { bg = "NONE", fg = "#c0caf5" })
hl(0, "CmpItemAbbrDeprecated", { bg = "NONE", fg = "#3b4261", strikethrough = true })
hl(0, "CmpItemAbbrMatch", { bg = "NONE", fg = "#2ac3de" })
hl(0, "CmpItemAbbrMatchFuzzy", { bg = "NONE", fg = "#2ac3de" })
hl(0, "CmpItemKindArray", { link = "LspKindArray" })
hl(0, "CmpItemKindBoolean", { link = "LspKindBoolean" })
hl(0, "CmpItemKindClass", { link = "LspKindClass" })
hl(0, "CmpItemKindCodeium", { bg = "NONE", fg = "#1abc9c" })
hl(0, "CmpItemKindColor", { link = "LspKindColor" })
hl(0, "CmpItemKindConstant", { link = "LspKindConstant" })
hl(0, "CmpItemKindConstructor", { link = "LspKindConstructor" })
hl(0, "CmpItemKindCopilot", { bg = "NONE", fg = "#1abc9c" })
hl(0, "CmpItemKindDefault", { bg = "NONE", fg = "#a9b1d6" })
hl(0, "CmpItemKindEnum", { link = "LspKindEnum" })
hl(0, "CmpItemKindEnumMember", { link = "LspKindEnumMember" })
hl(0, "CmpItemKindEvent", { link = "LspKindEvent" })
hl(0, "CmpItemKindField", { link = "LspKindField" })
hl(0, "CmpItemKindFile", { link = "LspKindFile" })
hl(0, "CmpItemKindFolder", { link = "LspKindFolder" })
hl(0, "CmpItemKindFunction", { link = "LspKindFunction" })
hl(0, "CmpItemKindInterface", { link = "LspKindInterface" })
hl(0, "CmpItemKindKey", { link = "LspKindKey" })
hl(0, "CmpItemKindKeyword", { link = "LspKindKeyword" })
hl(0, "CmpItemKindMethod", { link = "LspKindMethod" })
hl(0, "CmpItemKindModule", { link = "LspKindModule" })
hl(0, "CmpItemKindNamespace", { link = "LspKindNamespace" })
hl(0, "CmpItemKindNull", { link = "LspKindNull" })
hl(0, "CmpItemKindNumber", { link = "LspKindNumber" })
hl(0, "CmpItemKindObject", { link = "LspKindObject" })
hl(0, "CmpItemKindOperator", { link = "LspKindOperator" })
hl(0, "CmpItemKindPackage", { link = "LspKindPackage" })
hl(0, "CmpItemKindProperty", { link = "LspKindProperty" })
hl(0, "CmpItemKindReference", { link = "LspKindReference" })
hl(0, "CmpItemKindSnippet", { link = "LspKindSnippet" })
hl(0, "CmpItemKindString", { link = "LspKindString" })
hl(0, "CmpItemKindStruct", { link = "LspKindStruct" })
hl(0, "CmpItemKindSupermaven", { bg = "NONE", fg = "#1abc9c" })
hl(0, "CmpItemKindTabNine", { bg = "NONE", fg = "#1abc9c" })
hl(0, "CmpItemKindText", { link = "LspKindText" })
hl(0, "CmpItemKindTypeParameter", { link = "LspKindTypeParameter" })
hl(0, "CmpItemKindUnit", { link = "LspKindUnit" })
hl(0, "CmpItemKindValue", { link = "LspKindValue" })
hl(0, "CmpItemKindVariable", { link = "LspKindVariable" })
hl(0, "CmpItemMenu", { bg = "NONE", fg = "#565f89" })
hl(0, "CodeBlock", { bg = "#16161e" })
hl(0, "CodeiumSuggestion", { fg = "#414868" })
hl(0, "ColorColumn", { bg = "#15161e" })
hl(0, "Comment", { fg = "#565f89", italic = true })
hl(0, "ComplHint", { fg = "#414868" })
hl(0, "Conceal", { fg = "#737aa2" })
hl(0, "Constant", { fg = "#ff9e64" })
hl(0, "CopilotAnnotation", { fg = "#414868" })
hl(0, "CopilotSuggestion", { fg = "#414868" })
hl(0, "CurSearch", { link = "IncSearch" })
hl(0, "Cursor", { bg = "#c0caf5", fg = "#1a1b26" })
hl(0, "CursorColumn", { bg = "#292e42" })
hl(0, "CursorIM", { bg = "#c0caf5", fg = "#1a1b26" })
hl(0, "CursorLine", { bg = "#292e42" })
hl(0, "CursorLineNr", { bold = true, fg = "#ff9e64" })
hl(0, "DapStoppedLine", { bg = "#2e2a2d" })
hl(0, "DashboardDesc", { fg = "#7dcfff" })
hl(0, "DashboardFiles", { fg = "#7aa2f7" })
hl(0, "DashboardFooter", { fg = "#2ac3de" })
hl(0, "DashboardHeader", { fg = "#7aa2f7" })
hl(0, "DashboardIcon", { fg = "#7dcfff" })
hl(0, "DashboardKey", { fg = "#ff9e64" })
hl(0, "DashboardMruIcon", { fg = "#9d7cd8" })
hl(0, "DashboardMruTitle", { fg = "#7dcfff" })
hl(0, "DashboardProjectIcon", { fg = "#e0af68" })
hl(0, "DashboardProjectTitle", { fg = "#7dcfff" })
hl(0, "DashboardProjectTitleIcon", { fg = "#ff9e64" })
hl(0, "DashboardShortCut", { fg = "#7dcfff" })
hl(0, "DashboardShortCutIcon", { fg = "#bb9af7" })
hl(0, "Debug", { fg = "#ff9e64" })
hl(0, "DefinitionCount", { fg = "#9d7cd8" })
hl(0, "DefinitionIcon", { fg = "#7aa2f7" })
hl(0, "Delimiter", { link = "Special" })
hl(0, "DiagnosticError", { fg = "#db4b4b" })
hl(0, "DiagnosticHint", { fg = "#1abc9c" })
hl(0, "DiagnosticInfo", { fg = "#0db9d7" })
hl(0, "DiagnosticInformation", { link = "DiagnosticInfo" })
hl(0, "DiagnosticUnderlineError", { sp = "#db4b4b", undercurl = true })
hl(0, "DiagnosticUnderlineHint", { sp = "#1abc9c", undercurl = true })
hl(0, "DiagnosticUnderlineInfo", { sp = "#0db9d7", undercurl = true })
hl(0, "DiagnosticUnderlineWarn", { sp = "#e0af68", undercurl = true })
hl(0, "DiagnosticUnnecessary", { fg = "#414868" })
hl(0, "DiagnosticVirtualTextError", { bg = "#2d202a", fg = "#db4b4b" })
hl(0, "DiagnosticVirtualTextHint", { bg = "#1a2b32", fg = "#1abc9c" })
hl(0, "DiagnosticVirtualTextInfo", { bg = "#192b38", fg = "#0db9d7" })
hl(0, "DiagnosticVirtualTextWarn", { bg = "#2e2a2d", fg = "#e0af68" })
hl(0, "DiagnosticWarn", { fg = "#e0af68" })
hl(0, "DiagnosticWarning", { link = "DiagnosticWarn" })
hl(0, "DiffAdd", { bg = "#243e4a" })
hl(0, "DiffChange", { bg = "#1f2231" })
hl(0, "DiffDelete", { bg = "#4a272f" })
hl(0, "DiffText", { bg = "#394b70" })
hl(0, "Directory", { fg = "#7aa2f7" })
hl(0, "EndOfBuffer", { fg = "#1a1b26" })
hl(0, "Error", { fg = "#db4b4b" })
hl(0, "ErrorMsg", { fg = "#db4b4b" })
hl(0, "FlashBackdrop", { fg = "#545c7e" })
hl(0, "FlashLabel", { bg = "#ff007c", bold = true, fg = "#c0caf5" })
hl(0, "FloatBorder", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "FloatTitle", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "FoldColumn", { bg = "#1a1b26", fg = "#565f89" })
hl(0, "Folded", { bg = "#3b4261", fg = "#7aa2f7" })
hl(0, "Foo", { bg = "#ff007c", fg = "#c0caf5" })
hl(0, "Function", { fg = "#7aa2f7" })
hl(0, "FzfLuaBorder", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "FzfLuaCursor", { link = "IncSearch" })
hl(0, "FzfLuaDirPart", { fg = "#a9b1d6" })
hl(0, "FzfLuaFilePart", { link = "FzfLuaFzfNormal" })
hl(0, "FzfLuaFzfCursorLine", { link = "Visual" })
hl(0, "FzfLuaFzfNormal", { fg = "#c0caf5" })
hl(0, "FzfLuaFzfPointer", { fg = "#ff007c" })
hl(0, "FzfLuaFzfSeparator", { bg = "#16161e", fg = "#ff9e64" })
hl(0, "FzfLuaHeaderBind", { link = "@punctuation.special" })
hl(0, "FzfLuaHeaderText", { link = "Title" })
hl(0, "FzfLuaNormal", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "FzfLuaPath", { link = "Directory" })
hl(0, "FzfLuaPreviewTitle", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "FzfLuaTitle", { bg = "#16161e", fg = "#ff9e64" })
hl(0, "GitGutterAdd", { fg = "#449dab" })
hl(0, "GitGutterAddLineNr", { fg = "#449dab" })
hl(0, "GitGutterChange", { fg = "#6183bb" })
hl(0, "GitGutterChangeLineNr", { fg = "#6183bb" })
hl(0, "GitGutterDelete", { fg = "#914c54" })
hl(0, "GitGutterDeleteLineNr", { fg = "#914c54" })
hl(0, "GitSignsAdd", { fg = "#449dab" })
hl(0, "GitSignsChange", { fg = "#6183bb" })
hl(0, "GitSignsDelete", { fg = "#914c54" })
hl(0, "GlyphPalette1", { fg = "#db4b4b" })
hl(0, "GlyphPalette2", { fg = "#9ece6a" })
hl(0, "GlyphPalette3", { fg = "#e0af68" })
hl(0, "GlyphPalette4", { fg = "#7aa2f7" })
hl(0, "GlyphPalette6", { fg = "#73daca" })
hl(0, "GlyphPalette7", { fg = "#c0caf5" })
hl(0, "GlyphPalette9", { fg = "#f7768e" })
hl(0, "GrugFarHelpHeader", { fg = "#565f89" })
hl(0, "GrugFarHelpHeaderKey", { fg = "#7dcfff" })
hl(0, "GrugFarInputLabel", { fg = "#2ac3de" })
hl(0, "GrugFarInputPlaceholder", { fg = "#545c7e" })
hl(0, "GrugFarResultsChangeIndicator", { fg = "#6183bb" })
hl(0, "GrugFarResultsHeader", { fg = "#ff9e64" })
hl(0, "GrugFarResultsLineColumn", { fg = "#545c7e" })
hl(0, "GrugFarResultsLineNo", { fg = "#545c7e" })
hl(0, "GrugFarResultsMatch", { bg = "#f7768e", fg = "#15161e" })
hl(0, "GrugFarResultsStats", { fg = "#7aa2f7" })
hl(0, "Headline", { link = "Headline1" })
hl(0, "Headline1", { bg = "#1f2230" })
hl(0, "Headline2", { bg = "#242229" })
hl(0, "Headline3", { bg = "#212429" })
hl(0, "Headline4", { bg = "#1a232c" })
hl(0, "Headline5", { bg = "#222130" })
hl(0, "Headline6", { bg = "#21202f" })
hl(0, "Headline7", { bg = "#252229" })
hl(0, "Headline8", { bg = "#25202b" })
hl(0, "HopNextKey", { bold = true, fg = "#ff007c" })
hl(0, "HopNextKey1", { bold = true, fg = "#0db9d7" })
hl(0, "HopNextKey2", { fg = "#127a90" })
hl(0, "HopUnmatched", { fg = "#545c7e" })
hl(0, "IblIndent", { fg = "#3b4261", nocombine = true })
hl(0, "IblScope", { fg = "#2ac3de", nocombine = true })
hl(0, "Identifier", { fg = "#bb9af7" })
hl(0, "IlluminatedWordRead", { bg = "#3b4261" })
hl(0, "IlluminatedWordText", { bg = "#3b4261" })
hl(0, "IlluminatedWordWrite", { bg = "#3b4261" })
hl(0, "IncSearch", { bg = "#ff9e64", fg = "#15161e" })
hl(0, "IndentBlanklineChar", { fg = "#3b4261", nocombine = true })
hl(0, "IndentBlanklineContextChar", { fg = "#2ac3de", nocombine = true })
hl(0, "IndentLine", { fg = "#3b4261", nocombine = true })
hl(0, "IndentLineCurrent", { fg = "#2ac3de", nocombine = true })
hl(0, "Italic", { fg = "#c0caf5", italic = true })
hl(0, "Keyword", { fg = "#7dcfff", italic = true })
hl(0, "LazyProgressDone", { bold = true, fg = "#ff007c" })
hl(0, "LazyProgressTodo", { bold = true, fg = "#3b4261" })
hl(0, "LeapBackdrop", { fg = "#545c7e" })
hl(0, "LeapLabel", { bold = true, fg = "#ff007c" })
hl(0, "LeapMatch", { bg = "#ff007c", bold = true, fg = "#c0caf5" })
hl(0, "LineNr", { fg = "#3b4261" })
hl(0, "LineNrAbove", { fg = "#3b4261" })
hl(0, "LineNrBelow", { fg = "#3b4261" })
hl(0, "LspCodeLens", { fg = "#565f89" })
hl(0, "LspFloatWinBorder", { fg = "#27a1b9" })
hl(0, "LspFloatWinNormal", { bg = "#16161e" })
hl(0, "LspInfoBorder", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "LspInlayHint", { bg = "#1d202d", fg = "#545c7e" })
hl(0, "LspKindArray", { link = "@punctuation.bracket" })
hl(0, "LspKindBoolean", { link = "@boolean" })
hl(0, "LspKindClass", { link = "@type" })
hl(0, "LspKindColor", { link = "Special" })
hl(0, "LspKindConstant", { link = "@constant" })
hl(0, "LspKindConstructor", { link = "@constructor" })
hl(0, "LspKindEnum", { link = "@lsp.type.enum" })
hl(0, "LspKindEnumMember", { link = "@lsp.type.enumMember" })
hl(0, "LspKindEvent", { link = "Special" })
hl(0, "LspKindField", { link = "@variable.member" })
hl(0, "LspKindFile", { link = "Normal" })
hl(0, "LspKindFolder", { link = "Directory" })
hl(0, "LspKindFunction", { link = "@function" })
hl(0, "LspKindInterface", { link = "@lsp.type.interface" })
hl(0, "LspKindKey", { link = "@variable.member" })
hl(0, "LspKindKeyword", { link = "@lsp.type.keyword" })
hl(0, "LspKindMethod", { link = "@function.method" })
hl(0, "LspKindModule", { link = "@module" })
hl(0, "LspKindNamespace", { link = "@module" })
hl(0, "LspKindNull", { link = "@constant.builtin" })
hl(0, "LspKindNumber", { link = "@number" })
hl(0, "LspKindObject", { link = "@constant" })
hl(0, "LspKindOperator", { link = "@operator" })
hl(0, "LspKindPackage", { link = "@module" })
hl(0, "LspKindProperty", { link = "@property" })
hl(0, "LspKindReference", { link = "@markup.link" })
hl(0, "LspKindSnippet", { link = "Conceal" })
hl(0, "LspKindString", { link = "@string" })
hl(0, "LspKindStruct", { link = "@lsp.type.struct" })
hl(0, "LspKindText", { link = "@markup" })
hl(0, "LspKindTypeParameter", { link = "@lsp.type.typeParameter" })
hl(0, "LspKindUnit", { link = "@lsp.type.struct" })
hl(0, "LspKindValue", { link = "@string" })
hl(0, "LspKindVariable", { link = "@variable" })
hl(0, "LspReferenceRead", { bg = "#3b4261" })
hl(0, "LspReferenceText", { bg = "#3b4261" })
hl(0, "LspReferenceWrite", { bg = "#3b4261" })
hl(0, "LspSagaBorderTitle", { fg = "#7dcfff" })
hl(0, "LspSagaCodeActionBorder", { fg = "#7aa2f7" })
hl(0, "LspSagaCodeActionContent", { fg = "#9d7cd8" })
hl(0, "LspSagaCodeActionTitle", { fg = "#2ac3de" })
hl(0, "LspSagaDefPreviewBorder", { fg = "#9ece6a" })
hl(0, "LspSagaFinderSelection", { fg = "#283457" })
hl(0, "LspSagaHoverBorder", { fg = "#7aa2f7" })
hl(0, "LspSagaRenameBorder", { fg = "#9ece6a" })
hl(0, "LspSagaSignatureHelpBorder", { fg = "#f7768e" })
hl(0, "LspSignatureActiveParameter", { bg = "#20253a", bold = true })
hl(0, "MatchParen", { bold = true, fg = "#ff9e64" })
hl(0, "MiniAnimateCursor", { nocombine = true, reverse = true })
hl(0, "MiniAnimateNormalFloat", { link = "NormalFloat" })
hl(0, "MiniClueBorder", { link = "FloatBorder" })
hl(0, "MiniClueDescGroup", { link = "DiagnosticFloatingWarn" })
hl(0, "MiniClueDescSingle", { link = "NormalFloat" })
hl(0, "MiniClueNextKey", { link = "DiagnosticFloatingHint" })
hl(0, "MiniClueNextKeyWithPostkeys", { link = "DiagnosticFloatingError" })
hl(0, "MiniClueSeparator", { link = "DiagnosticFloatingInfo" })
hl(0, "MiniClueTitle", { link = "FloatTitle" })
hl(0, "MiniCompletionActiveParameter", { underline = true })
hl(0, "MiniCursorword", { bg = "#3b4261" })
hl(0, "MiniCursorwordCurrent", { bg = "#3b4261" })
hl(0, "MiniDepsChangeAdded", { link = "diffAdded" })
hl(0, "MiniDepsChangeRemoved", { link = "diffRemoved" })
hl(0, "MiniDepsHint", { link = "DiagnosticHint" })
hl(0, "MiniDepsInfo", { link = "DiagnosticInfo" })
hl(0, "MiniDepsMsgBreaking", { link = "DiagnosticWarn" })
hl(0, "MiniDepsPlaceholder", { link = "Comment" })
hl(0, "MiniDepsTitle", { link = "Title" })
hl(0, "MiniDepsTitleError", { bg = "#914c54", fg = "#15161e" })
hl(0, "MiniDepsTitleSame", { link = "Comment" })
hl(0, "MiniDepsTitleUpdate", { bg = "#449dab", fg = "#15161e" })
hl(0, "MiniDiffOverAdd", { link = "DiffAdd" })
hl(0, "MiniDiffOverChange", { link = "DiffText" })
hl(0, "MiniDiffOverContext", { link = "DiffChange" })
hl(0, "MiniDiffOverDelete", { link = "DiffDelete" })
hl(0, "MiniDiffSignAdd", { fg = "#449dab" })
hl(0, "MiniDiffSignChange", { fg = "#6183bb" })
hl(0, "MiniDiffSignDelete", { fg = "#914c54" })
hl(0, "MiniFilesBorder", { link = "FloatBorder" })
hl(0, "MiniFilesBorderModified", { link = "DiagnosticFloatingWarn" })
hl(0, "MiniFilesCursorLine", { link = "CursorLine" })
hl(0, "MiniFilesDirectory", { link = "Directory" })
hl(0, "MiniFilesFile", { fg = "#c0caf5" })
hl(0, "MiniFilesNormal", { link = "NormalFloat" })
hl(0, "MiniFilesTitle", { link = "FloatTitle" })
hl(0, "MiniFilesTitleFocused", { bg = "#16161e", bold = true, fg = "#27a1b9" })
hl(0, "MiniHipatternsFixme", { bg = "#db4b4b", bold = true, fg = "#15161e" })
hl(0, "MiniHipatternsHack", { bg = "#e0af68", bold = true, fg = "#15161e" })
hl(0, "MiniHipatternsNote", { bg = "#1abc9c", bold = true, fg = "#15161e" })
hl(0, "MiniHipatternsTodo", { bg = "#0db9d7", bold = true, fg = "#15161e" })
hl(0, "MiniIconsAzure", { fg = "#0db9d7" })
hl(0, "MiniIconsBlue", { fg = "#7aa2f7" })
hl(0, "MiniIconsCyan", { fg = "#1abc9c" })
hl(0, "MiniIconsGreen", { fg = "#9ece6a" })
hl(0, "MiniIconsGrey", { fg = "#c0caf5" })
hl(0, "MiniIconsOrange", { fg = "#ff9e64" })
hl(0, "MiniIconsPurple", { fg = "#9d7cd8" })
hl(0, "MiniIconsRed", { fg = "#f7768e" })
hl(0, "MiniIconsYellow", { fg = "#e0af68" })
hl(0, "MiniIndentscopePrefix", { nocombine = true })
hl(0, "MiniIndentscopeSymbol", { fg = "#2ac3de", nocombine = true })
hl(0, "MiniJump", { bg = "#ff007c", fg = "#ffffff" })
hl(0, "MiniJump2dDim", { link = "Comment" })
hl(0, "MiniJump2dSpot", { bold = true, fg = "#ff007c", nocombine = true })
hl(0, "MiniJump2dSpotAhead", { bg = "#16161e", fg = "#1abc9c", nocombine = true })
hl(0, "MiniJump2dSpotUnique", { bold = true, fg = "#ff9e64", nocombine = true })
hl(0, "MiniMapNormal", { link = "NormalFloat" })
hl(0, "MiniMapSymbolCount", { link = "Special" })
hl(0, "MiniMapSymbolLine", { link = "Title" })
hl(0, "MiniMapSymbolView", { link = "Delimiter" })
hl(0, "MiniNotifyBorder", { link = "FloatBorder" })
hl(0, "MiniNotifyNormal", { link = "NormalFloat" })
hl(0, "MiniNotifyTitle", { link = "FloatTitle" })
hl(0, "MiniOperatorsExchangeFrom", { link = "IncSearch" })
hl(0, "MiniPickBorder", { link = "FloatBorder" })
hl(0, "MiniPickBorderBusy", { link = "DiagnosticFloatingWarn" })
hl(0, "MiniPickBorderText", { bg = "#16161e", fg = "#1abc9c" })
hl(0, "MiniPickHeader", { link = "DiagnosticFloatingHint" })
hl(0, "MiniPickIconDirectory", { link = "Directory" })
hl(0, "MiniPickIconFile", { link = "MiniPickNormal" })
hl(0, "MiniPickMatchCurrent", { link = "CursorLine" })
hl(0, "MiniPickMatchMarked", { link = "Visual" })
hl(0, "MiniPickMatchRanges", { link = "DiagnosticFloatingHint" })
hl(0, "MiniPickNormal", { link = "NormalFloat" })
hl(0, "MiniPickPreviewLine", { link = "CursorLine" })
hl(0, "MiniPickPreviewRegion", { link = "IncSearch" })
hl(0, "MiniPickPrompt", { bg = "#16161e", fg = "#0db9d7" })
hl(0, "MiniStarterCurrent", { nocombine = true })
hl(0, "MiniStarterFooter", { fg = "#e0af68", italic = true })
hl(0, "MiniStarterHeader", { fg = "#7aa2f7" })
hl(0, "MiniStarterInactive", { fg = "#565f89", italic = true })
hl(0, "MiniStarterItem", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "MiniStarterItemBullet", { fg = "#27a1b9" })
hl(0, "MiniStarterItemPrefix", { fg = "#e0af68" })
hl(0, "MiniStarterQuery", { fg = "#0db9d7" })
hl(0, "MiniStarterSection", { fg = "#2ac3de" })
hl(0, "MiniStatuslineDevinfo", { bg = "#3b4261", fg = "#a9b1d6" })
hl(0, "MiniStatuslineFileinfo", { bg = "#3b4261", fg = "#a9b1d6" })
hl(0, "MiniStatuslineFilename", { bg = "#292e42", fg = "#a9b1d6" })
hl(0, "MiniStatuslineInactive", { bg = "#16161e", fg = "#7aa2f7" })
hl(0, "MiniStatuslineModeCommand", { bg = "#e0af68", bold = true, fg = "#15161e" })
hl(0, "MiniStatuslineModeInsert", { bg = "#9ece6a", bold = true, fg = "#15161e" })
hl(0, "MiniStatuslineModeNormal", { bg = "#7aa2f7", bold = true, fg = "#15161e" })
hl(0, "MiniStatuslineModeOther", { bg = "#1abc9c", bold = true, fg = "#15161e" })
hl(0, "MiniStatuslineModeReplace", { bg = "#f7768e", bold = true, fg = "#15161e" })
hl(0, "MiniStatuslineModeVisual", { bg = "#bb9af7", bold = true, fg = "#15161e" })
hl(0, "MiniSurround", { bg = "#ff9e64", fg = "#15161e" })
hl(0, "MiniTablineCurrent", { bg = "#3b4261", fg = "#c0caf5" })
hl(0, "MiniTablineFill", { bg = "#15161e" })
hl(0, "MiniTablineHidden", { bg = "#16161e", fg = "#737aa2" })
hl(0, "MiniTablineModifiedCurrent", { bg = "#3b4261", fg = "#e0af68" })
hl(0, "MiniTablineModifiedHidden", { bg = "#16161e", fg = "#a58354" })
hl(0, "MiniTablineModifiedVisible", { bg = "#16161e", fg = "#e0af68" })
hl(0, "MiniTablineTabpagesection", { bg = "#3b4261", fg = "NONE" })
hl(0, "MiniTablineVisible", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "MiniTestEmphasis", { bold = true })
hl(0, "MiniTestFail", { bold = true, fg = "#f7768e" })
hl(0, "MiniTestPass", { bold = true, fg = "#9ece6a" })
hl(0, "MiniTrailspace", { bg = "#f7768e" })
hl(0, "ModeMsg", { bold = true, fg = "#a9b1d6" })
hl(0, "MoreMsg", { fg = "#7aa2f7" })
hl(0, "MsgArea", { fg = "#a9b1d6" })
hl(0, "NavicIconsArray", { link = "LspKindArray" })
hl(0, "NavicIconsBoolean", { link = "LspKindBoolean" })
hl(0, "NavicIconsClass", { link = "LspKindClass" })
hl(0, "NavicIconsColor", { link = "LspKindColor" })
hl(0, "NavicIconsConstant", { link = "LspKindConstant" })
hl(0, "NavicIconsConstructor", { link = "LspKindConstructor" })
hl(0, "NavicIconsEnum", { link = "LspKindEnum" })
hl(0, "NavicIconsEnumMember", { link = "LspKindEnumMember" })
hl(0, "NavicIconsEvent", { link = "LspKindEvent" })
hl(0, "NavicIconsField", { link = "LspKindField" })
hl(0, "NavicIconsFile", { link = "LspKindFile" })
hl(0, "NavicIconsFolder", { link = "LspKindFolder" })
hl(0, "NavicIconsFunction", { link = "LspKindFunction" })
hl(0, "NavicIconsInterface", { link = "LspKindInterface" })
hl(0, "NavicIconsKey", { link = "LspKindKey" })
hl(0, "NavicIconsKeyword", { link = "LspKindKeyword" })
hl(0, "NavicIconsMethod", { link = "LspKindMethod" })
hl(0, "NavicIconsModule", { link = "LspKindModule" })
hl(0, "NavicIconsNamespace", { link = "LspKindNamespace" })
hl(0, "NavicIconsNull", { link = "LspKindNull" })
hl(0, "NavicIconsNumber", { link = "LspKindNumber" })
hl(0, "NavicIconsObject", { link = "LspKindObject" })
hl(0, "NavicIconsOperator", { link = "LspKindOperator" })
hl(0, "NavicIconsPackage", { link = "LspKindPackage" })
hl(0, "NavicIconsProperty", { link = "LspKindProperty" })
hl(0, "NavicIconsReference", { link = "LspKindReference" })
hl(0, "NavicIconsSnippet", { link = "LspKindSnippet" })
hl(0, "NavicIconsString", { link = "LspKindString" })
hl(0, "NavicIconsStruct", { link = "LspKindStruct" })
hl(0, "NavicIconsText", { link = "LspKindText" })
hl(0, "NavicIconsTypeParameter", { link = "LspKindTypeParameter" })
hl(0, "NavicIconsUnit", { link = "LspKindUnit" })
hl(0, "NavicIconsValue", { link = "LspKindValue" })
hl(0, "NavicIconsVariable", { link = "LspKindVariable" })
hl(0, "NavicSeparator", { bg = "NONE", fg = "#c0caf5" })
hl(0, "NavicText", { bg = "NONE", fg = "#c0caf5" })
hl(0, "NeoTreeDimText", { fg = "#3b4261" })
hl(0, "NeoTreeFileName", { fg = "#a9b1d6" })
hl(0, "NeoTreeGitModified", { fg = "#ff9e64" })
hl(0, "NeoTreeGitStaged", { fg = "#73daca" })
hl(0, "NeoTreeGitUntracked", { fg = "#bb9af7" })
hl(0, "NeoTreeNormal", { bg = "#16161e", fg = "#a9b1d6" })
hl(0, "NeoTreeNormalNC", { bg = "#16161e", fg = "#a9b1d6" })
hl(0, "NeoTreeTabActive", { bg = "#16161e", bold = true, fg = "#7aa2f7" })
hl(0, "NeoTreeTabInactive", { bg = "#121218", fg = "#545c7e" })
hl(0, "NeoTreeTabSeparatorActive", { bg = "#16161e", fg = "#7aa2f7" })
hl(0, "NeoTreeTabSeparatorInactive", { bg = "#121218", fg = "#1a1b26" })
hl(0, "NeogitBranch", { fg = "#bb9af7" })
hl(0, "NeogitDiffAddHighlight", { bg = "#243e4a", fg = "#449dab" })
hl(0, "NeogitDiffContextHighlight", { bg = "#2b2f44", fg = "#a9b1d6" })
hl(0, "NeogitDiffDeleteHighlight", { bg = "#4a272f", fg = "#914c54" })
hl(0, "NeogitHunkHeader", { bg = "#292e42", fg = "#c0caf5" })
hl(0, "NeogitHunkHeaderHighlight", { bg = "#3b4261", fg = "#7aa2f7" })
hl(0, "NeogitRemote", { fg = "#9d7cd8" })
hl(0, "NeotestAdapterName", { bold = true, fg = "#9d7cd8" })
hl(0, "NeotestBorder", { fg = "#7aa2f7" })
hl(0, "NeotestDir", { fg = "#7aa2f7" })
hl(0, "NeotestExpandMarker", { fg = "#a9b1d6" })
hl(0, "NeotestFailed", { fg = "#f7768e" })
hl(0, "NeotestFile", { fg = "#1abc9c" })
hl(0, "NeotestFocused", { fg = "#e0af68" })
hl(0, "NeotestIndent", { fg = "#a9b1d6" })
hl(0, "NeotestMarked", { fg = "#7aa2f7" })
hl(0, "NeotestNamespace", { fg = "#41a6b5" })
hl(0, "NeotestPassed", { fg = "#9ece6a" })
hl(0, "NeotestRunning", { fg = "#e0af68" })
hl(0, "NeotestSkipped", { fg = "#7aa2f7" })
hl(0, "NeotestTarget", { fg = "#7aa2f7" })
hl(0, "NeotestTest", { fg = "#a9b1d6" })
hl(0, "NeotestWinSelect", { fg = "#7aa2f7" })
hl(0, "NoiceCmdlineIconInput", { fg = "#e0af68" })
hl(0, "NoiceCmdlineIconLua", { fg = "#2ac3de" })
hl(0, "NoiceCmdlinePopupBorderInput", { fg = "#e0af68" })
hl(0, "NoiceCmdlinePopupBorderLua", { fg = "#2ac3de" })
hl(0, "NoiceCmdlinePopupTitleInput", { fg = "#e0af68" })
hl(0, "NoiceCmdlinePopupTitleLua", { fg = "#2ac3de" })
hl(0, "NoiceCompletionItemKindArray", { link = "LspKindArray" })
hl(0, "NoiceCompletionItemKindBoolean", { link = "LspKindBoolean" })
hl(0, "NoiceCompletionItemKindClass", { link = "LspKindClass" })
hl(0, "NoiceCompletionItemKindColor", { link = "LspKindColor" })
hl(0, "NoiceCompletionItemKindConstant", { link = "LspKindConstant" })
hl(0, "NoiceCompletionItemKindConstructor", { link = "LspKindConstructor" })
hl(0, "NoiceCompletionItemKindDefault", { bg = "NONE", fg = "#a9b1d6" })
hl(0, "NoiceCompletionItemKindEnum", { link = "LspKindEnum" })
hl(0, "NoiceCompletionItemKindEnumMember", { link = "LspKindEnumMember" })
hl(0, "NoiceCompletionItemKindEvent", { link = "LspKindEvent" })
hl(0, "NoiceCompletionItemKindField", { link = "LspKindField" })
hl(0, "NoiceCompletionItemKindFile", { link = "LspKindFile" })
hl(0, "NoiceCompletionItemKindFolder", { link = "LspKindFolder" })
hl(0, "NoiceCompletionItemKindFunction", { link = "LspKindFunction" })
hl(0, "NoiceCompletionItemKindInterface", { link = "LspKindInterface" })
hl(0, "NoiceCompletionItemKindKey", { link = "LspKindKey" })
hl(0, "NoiceCompletionItemKindKeyword", { link = "LspKindKeyword" })
hl(0, "NoiceCompletionItemKindMethod", { link = "LspKindMethod" })
hl(0, "NoiceCompletionItemKindModule", { link = "LspKindModule" })
hl(0, "NoiceCompletionItemKindNamespace", { link = "LspKindNamespace" })
hl(0, "NoiceCompletionItemKindNull", { link = "LspKindNull" })
hl(0, "NoiceCompletionItemKindNumber", { link = "LspKindNumber" })
hl(0, "NoiceCompletionItemKindObject", { link = "LspKindObject" })
hl(0, "NoiceCompletionItemKindOperator", { link = "LspKindOperator" })
hl(0, "NoiceCompletionItemKindPackage", { link = "LspKindPackage" })
hl(0, "NoiceCompletionItemKindProperty", { link = "LspKindProperty" })
hl(0, "NoiceCompletionItemKindReference", { link = "LspKindReference" })
hl(0, "NoiceCompletionItemKindSnippet", { link = "LspKindSnippet" })
hl(0, "NoiceCompletionItemKindString", { link = "LspKindString" })
hl(0, "NoiceCompletionItemKindStruct", { link = "LspKindStruct" })
hl(0, "NoiceCompletionItemKindText", { link = "LspKindText" })
hl(0, "NoiceCompletionItemKindTypeParameter", { link = "LspKindTypeParameter" })
hl(0, "NoiceCompletionItemKindUnit", { link = "LspKindUnit" })
hl(0, "NoiceCompletionItemKindValue", { link = "LspKindValue" })
hl(0, "NoiceCompletionItemKindVariable", { link = "LspKindVariable" })
hl(0, "NonText", { fg = "#545c7e" })
hl(0, "Normal", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "NormalFloat", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "NormalNC", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "NormalSB", { bg = "#16161e", fg = "#a9b1d6" })
hl(0, "NotifyBackground", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "NotifyDEBUGBody", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "NotifyDEBUGBorder", { bg = "#1a1b26", fg = "#2c2f44" })
hl(0, "NotifyDEBUGIcon", { fg = "#565f89" })
hl(0, "NotifyDEBUGTitle", { fg = "#565f89" })
hl(0, "NotifyERRORBody", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "NotifyERRORBorder", { bg = "#1a1b26", fg = "#542931" })
hl(0, "NotifyERRORIcon", { fg = "#db4b4b" })
hl(0, "NotifyERRORTitle", { fg = "#db4b4b" })
hl(0, "NotifyINFOBody", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "NotifyINFOBorder", { bg = "#1a1b26", fg = "#164a5b" })
hl(0, "NotifyINFOIcon", { fg = "#0db9d7" })
hl(0, "NotifyINFOTitle", { fg = "#0db9d7" })
hl(0, "NotifyTRACEBody", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "NotifyTRACEBorder", { bg = "#1a1b26", fg = "#41385b" })
hl(0, "NotifyTRACEIcon", { fg = "#9d7cd8" })
hl(0, "NotifyTRACETitle", { fg = "#9d7cd8" })
hl(0, "NotifyWARNBody", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "NotifyWARNBorder", { bg = "#1a1b26", fg = "#55473a" })
hl(0, "NotifyWARNIcon", { fg = "#e0af68" })
hl(0, "NotifyWARNTitle", { fg = "#e0af68" })
hl(0, "NvimTreeFolderIcon", { bg = "NONE", fg = "#7aa2f7" })
hl(0, "NvimTreeGitDeleted", { fg = "#914c54" })
hl(0, "NvimTreeGitDirty", { fg = "#6183bb" })
hl(0, "NvimTreeGitNew", { fg = "#449dab" })
hl(0, "NvimTreeImageFile", { fg = "#a9b1d6" })
hl(0, "NvimTreeIndentMarker", { fg = "#3b4261" })
hl(0, "NvimTreeNormal", { bg = "#16161e", fg = "#a9b1d6" })
hl(0, "NvimTreeNormalNC", { bg = "#16161e", fg = "#a9b1d6" })
hl(0, "NvimTreeOpenedFile", { bg = "#292e42" })
hl(0, "NvimTreeRootFolder", { bold = true, fg = "#7aa2f7" })
hl(0, "NvimTreeSpecialFile", { fg = "#9d7cd8", underline = true })
hl(0, "NvimTreeSymlink", { fg = "#7aa2f7" })
hl(0, "NvimTreeWinSeparator", { bg = "#16161e", fg = "#16161e" })
hl(0, "OctoDetailsLabel", { bold = true, fg = "#2ac3de" })
hl(0, "OctoDetailsValue", { link = "@variable.member" })
hl(0, "OctoDirty", { bold = true, fg = "#ff9e64" })
hl(0, "OctoIssueTitle", { bold = true, fg = "#9d7cd8" })
hl(0, "OctoStateChangesRequested", { link = "DiagnosticVirtualTextWarn" })
hl(0, "OctoStateClosed", { link = "DiagnosticVirtualTextError" })
hl(0, "OctoStateMerged", { bg = "#2a283b", fg = "#bb9af7" })
hl(0, "OctoStateOpen", { link = "DiagnosticVirtualTextHint" })
hl(0, "OctoStatePending", { link = "DiagnosticVirtualTextWarn" })
hl(0, "OctoStatusColumn", { fg = "#2ac3de" })
hl(0, "Operator", { fg = "#89ddff" })
hl(0, "Pmenu", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "PmenuMatch", { bg = "#16161e", fg = "#2ac3de" })
hl(0, "PmenuMatchSel", { bg = "#343a55", fg = "#2ac3de" })
hl(0, "PmenuSbar", { bg = "#1f1f29" })
hl(0, "PmenuSel", { bg = "#343a55" })
hl(0, "PmenuThumb", { bg = "#3b4261" })
hl(0, "PreProc", { fg = "#7dcfff" })
hl(0, "Question", { fg = "#7aa2f7" })
hl(0, "QuickFixLine", { bg = "#283457", bold = true })
hl(0, "RainbowDelimiterBlue", { fg = "#7aa2f7" })
hl(0, "RainbowDelimiterCyan", { fg = "#7dcfff" })
hl(0, "RainbowDelimiterGreen", { fg = "#9ece6a" })
hl(0, "RainbowDelimiterOrange", { fg = "#ff9e64" })
hl(0, "RainbowDelimiterRed", { fg = "#f7768e" })
hl(0, "RainbowDelimiterViolet", { fg = "#9d7cd8" })
hl(0, "RainbowDelimiterYellow", { fg = "#e0af68" })
hl(0, "ReferencesCount", { fg = "#9d7cd8" })
hl(0, "ReferencesIcon", { fg = "#7aa2f7" })
hl(0, "RenderMarkdownBullet", { fg = "#ff9e64" })
hl(0, "RenderMarkdownCode", { bg = "#16161e" })
hl(0, "RenderMarkdownCodeInline", { link = "@markup.raw.markdown_inline" })
hl(0, "RenderMarkdownDash", { fg = "#ff9e64" })
hl(0, "RenderMarkdownH1Bg", { bg = "#24293b" })
hl(0, "RenderMarkdownH1Fg", { bold = true, fg = "#7aa2f7" })
hl(0, "RenderMarkdownH2Bg", { bg = "#2e2a2d" })
hl(0, "RenderMarkdownH2Fg", { bold = true, fg = "#e0af68" })
hl(0, "RenderMarkdownH3Bg", { bg = "#272d2d" })
hl(0, "RenderMarkdownH3Fg", { bold = true, fg = "#9ece6a" })
hl(0, "RenderMarkdownH4Bg", { bg = "#1a2b32" })
hl(0, "RenderMarkdownH4Fg", { bold = true, fg = "#1abc9c" })
hl(0, "RenderMarkdownH5Bg", { bg = "#2a283b" })
hl(0, "RenderMarkdownH5Fg", { bold = true, fg = "#bb9af7" })
hl(0, "RenderMarkdownH6Bg", { bg = "#272538" })
hl(0, "RenderMarkdownH6Fg", { bold = true, fg = "#9d7cd8" })
hl(0, "RenderMarkdownH7Bg", { bg = "#31282c" })
hl(0, "RenderMarkdownH7Fg", { bold = true, fg = "#ff9e64" })
hl(0, "RenderMarkdownH8Bg", { bg = "#302430" })
hl(0, "RenderMarkdownH8Fg", { bold = true, fg = "#f7768e" })
hl(0, "RenderMarkdownTableHead", { fg = "#f7768e" })
hl(0, "RenderMarkdownTableRow", { fg = "#ff9e64" })
hl(0, "ScrollbarError", { bg = "NONE", fg = "#db4b4b" })
hl(0, "ScrollbarErrorHandle", { bg = "#292e42", fg = "#db4b4b" })
hl(0, "ScrollbarHandle", { bg = "#292e42", fg = "NONE" })
hl(0, "ScrollbarHint", { bg = "NONE", fg = "#1abc9c" })
hl(0, "ScrollbarHintHandle", { bg = "#292e42", fg = "#1abc9c" })
hl(0, "ScrollbarInfo", { bg = "NONE", fg = "#0db9d7" })
hl(0, "ScrollbarInfoHandle", { bg = "#292e42", fg = "#0db9d7" })
hl(0, "ScrollbarMisc", { bg = "NONE", fg = "#9d7cd8" })
hl(0, "ScrollbarMiscHandle", { bg = "#292e42", fg = "#9d7cd8" })
hl(0, "ScrollbarSearch", { bg = "NONE", fg = "#ff9e64" })
hl(0, "ScrollbarSearchHandle", { bg = "#292e42", fg = "#ff9e64" })
hl(0, "ScrollbarWarn", { bg = "NONE", fg = "#e0af68" })
hl(0, "ScrollbarWarnHandle", { bg = "#292e42", fg = "#e0af68" })
hl(0, "Search", { bg = "#3d59a1", fg = "#c0caf5" })
hl(0, "SidekickDiffAdd", { link = "DiffAdd" })
hl(0, "SidekickDiffContext", { link = "DiffChange" })
hl(0, "SidekickDiffDelete", { link = "DiffDelete" })
hl(0, "SidekickSignAdd", { fg = "#449dab" })
hl(0, "SidekickSignChange", { fg = "#6183bb" })
hl(0, "SidekickSignDelete", { fg = "#914c54" })
hl(0, "SignColumn", { bg = "#1a1b26", fg = "#3b4261" })
hl(0, "SignColumnSB", { bg = "#16161e", fg = "#3b4261" })
hl(0, "SnacksDashboardDesc", { fg = "#7dcfff" })
hl(0, "SnacksDashboardDir", { fg = "#545c7e" })
hl(0, "SnacksDashboardFooter", { fg = "#2ac3de" })
hl(0, "SnacksDashboardHeader", { fg = "#7aa2f7" })
hl(0, "SnacksDashboardIcon", { fg = "#2ac3de" })
hl(0, "SnacksDashboardKey", { fg = "#ff9e64" })
hl(0, "SnacksDashboardSpecial", { fg = "#9d7cd8" })
hl(0, "SnacksDiffLabel", { bold = true, fg = "#2ac3de" })
hl(0, "SnacksFooterDesc", { link = "SnacksProfilerBadgeInfo" })
hl(0, "SnacksFooterKey", { link = "SnacksProfilerIconInfo" })
hl(0, "SnacksGhDiffHeader", { bg = "#1c2c38", fg = "#2ac3de" })
hl(0, "SnacksGhLabel", { bold = true, fg = "#2ac3de" })
hl(0, "SnacksIndent", { fg = "#3b4261", nocombine = true })
hl(0, "SnacksIndent1", { fg = "#7aa2f7", nocombine = true })
hl(0, "SnacksIndent2", { fg = "#e0af68", nocombine = true })
hl(0, "SnacksIndent3", { fg = "#9ece6a", nocombine = true })
hl(0, "SnacksIndent4", { fg = "#1abc9c", nocombine = true })
hl(0, "SnacksIndent5", { fg = "#bb9af7", nocombine = true })
hl(0, "SnacksIndent6", { fg = "#9d7cd8", nocombine = true })
hl(0, "SnacksIndent7", { fg = "#ff9e64", nocombine = true })
hl(0, "SnacksIndent8", { fg = "#f7768e", nocombine = true })
hl(0, "SnacksIndentScope", { fg = "#2ac3de", nocombine = true })
hl(0, "SnacksInputBorder", { fg = "#e0af68" })
hl(0, "SnacksInputIcon", { fg = "#2ac3de" })
hl(0, "SnacksInputTitle", { fg = "#e0af68" })
hl(0, "SnacksNotifierBorderDebug", { bg = "#1a1b26", fg = "#32364e" })
hl(0, "SnacksNotifierBorderError", { bg = "#1a1b26", fg = "#672e35" })
hl(0, "SnacksNotifierBorderInfo", { bg = "#1a1b26", fg = "#155a6d" })
hl(0, "SnacksNotifierBorderTrace", { bg = "#1a1b26", fg = "#4e426d" })
hl(0, "SnacksNotifierBorderWarn", { bg = "#1a1b26", fg = "#695640" })
hl(0, "SnacksNotifierDebug", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "SnacksNotifierError", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "SnacksNotifierIconDebug", { fg = "#565f89" })
hl(0, "SnacksNotifierIconError", { fg = "#db4b4b" })
hl(0, "SnacksNotifierIconInfo", { fg = "#0db9d7" })
hl(0, "SnacksNotifierIconTrace", { fg = "#9d7cd8" })
hl(0, "SnacksNotifierIconWarn", { fg = "#e0af68" })
hl(0, "SnacksNotifierInfo", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "SnacksNotifierTitleDebug", { fg = "#565f89" })
hl(0, "SnacksNotifierTitleError", { fg = "#db4b4b" })
hl(0, "SnacksNotifierTitleInfo", { fg = "#0db9d7" })
hl(0, "SnacksNotifierTitleTrace", { fg = "#9d7cd8" })
hl(0, "SnacksNotifierTitleWarn", { fg = "#e0af68" })
hl(0, "SnacksNotifierTrace", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "SnacksNotifierWarn", { bg = "#1a1b26", fg = "#c0caf5" })
hl(0, "SnacksPickerBoxTitle", { bg = "#16161e", fg = "#ff9e64" })
hl(0, "SnacksPickerInputBorder", { bg = "#16161e", fg = "#ff9e64" })
hl(0, "SnacksPickerInputTitle", { bg = "#16161e", fg = "#ff9e64" })
hl(0, "SnacksPickerPickWin", { bg = "#3d59a1", bold = true, fg = "#c0caf5" })
hl(0, "SnacksPickerPickWinCurrent", { bg = "#ff007c", bold = true, fg = "#c0caf5" })
hl(0, "SnacksPickerSelected", { fg = "#ff007c" })
hl(0, "SnacksPickerToggle", { link = "SnacksProfilerBadgeInfo" })
hl(0, "SnacksProfilerBadgeInfo", { bg = "#1c2c38", fg = "#2ac3de" })
hl(0, "SnacksProfilerBadgeTrace", { bg = "#1d202d", fg = "#545c7e" })
hl(0, "SnacksProfilerIconInfo", { bg = "#1f4d5d", fg = "#2ac3de" })
hl(0, "SnacksProfilerIconTrace", { bg = "#23293c", fg = "#545c7e" })
hl(0, "SnacksZenIcon", { fg = "#9d7cd8" })
hl(0, "Sneak", { bg = "#bb9af7", fg = "#292e42" })
hl(0, "SneakScope", { bg = "#283457" })
hl(0, "Special", { fg = "#2ac3de" })
hl(0, "SpecialKey", { fg = "#545c7e" })
hl(0, "SpellBad", { sp = "#db4b4b", undercurl = true })
hl(0, "SpellCap", { sp = "#e0af68", undercurl = true })
hl(0, "SpellLocal", { sp = "#0db9d7", undercurl = true })
hl(0, "SpellRare", { sp = "#1abc9c", undercurl = true })
hl(0, "Statement", { fg = "#bb9af7" })
hl(0, "StatusLine", { bg = "#16161e", fg = "#a9b1d6" })
hl(0, "StatusLineNC", { bg = "#16161e", fg = "#3b4261" })
hl(0, "String", { fg = "#9ece6a" })
hl(0, "Substitute", { bg = "#f7768e", fg = "#15161e" })
hl(0, "SupermavenSuggestion", { fg = "#414868" })
hl(0, "TabLine", { bg = "#16161e", fg = "#3b4261" })
hl(0, "TabLineFill", { bg = "#15161e" })
hl(0, "TabLineSel", { bg = "#7aa2f7", fg = "#15161e" })
hl(0, "TargetWord", { fg = "#7dcfff" })
hl(0, "TelescopeBorder", { bg = "#16161e", fg = "#27a1b9" })
hl(0, "TelescopeNormal", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "TelescopePromptBorder", { bg = "#16161e", fg = "#ff9e64" })
hl(0, "TelescopePromptTitle", { bg = "#16161e", fg = "#ff9e64" })
hl(0, "TelescopeResultsComment", { fg = "#545c7e" })
hl(0, "Title", { bold = true, fg = "#7aa2f7" })
hl(0, "Todo", { bg = "#e0af68", fg = "#1a1b26" })
hl(0, "TreesitterContext", { bg = "#343a55" })
hl(0, "TroubleCount", { bg = "#3b4261", fg = "#bb9af7" })
hl(0, "TroubleNormal", { bg = "#16161e", fg = "#c0caf5" })
hl(0, "TroubleText", { fg = "#a9b1d6" })
hl(0, "Type", { fg = "#2ac3de" })
hl(0, "Underlined", { underline = true })
hl(0, "VertSplit", { fg = "#15161e" })
hl(0, "VimwikiHR", { bg = "NONE", fg = "#e0af68" })
hl(0, "VimwikiHeader1", { bg = "NONE", bold = true, fg = "#7aa2f7" })
hl(0, "VimwikiHeader2", { bg = "NONE", bold = true, fg = "#e0af68" })
hl(0, "VimwikiHeader3", { bg = "NONE", bold = true, fg = "#9ece6a" })
hl(0, "VimwikiHeader4", { bg = "NONE", bold = true, fg = "#1abc9c" })
hl(0, "VimwikiHeader5", { bg = "NONE", bold = true, fg = "#bb9af7" })
hl(0, "VimwikiHeader6", { bg = "NONE", bold = true, fg = "#9d7cd8" })
hl(0, "VimwikiHeader7", { bg = "NONE", bold = true, fg = "#ff9e64" })
hl(0, "VimwikiHeader8", { bg = "NONE", bold = true, fg = "#f7768e" })
hl(0, "VimwikiHeaderChar", { bg = "NONE", fg = "#e0af68" })
hl(0, "VimwikiLink", { bg = "NONE", fg = "#7aa2f7" })
hl(0, "VimwikiList", { bg = "NONE", fg = "#ff9e64" })
hl(0, "VimwikiMarkers", { bg = "NONE", fg = "#7aa2f7" })
hl(0, "VimwikiTag", { bg = "NONE", fg = "#9ece6a" })
hl(0, "Visual", { bg = "#283457" })
hl(0, "VisualNOS", { bg = "#283457" })
hl(0, "WarningMsg", { fg = "#e0af68" })
hl(0, "WhichKey", { fg = "#7dcfff" })
hl(0, "WhichKeyDesc", { fg = "#bb9af7" })
hl(0, "WhichKeyGroup", { fg = "#7aa2f7" })
hl(0, "WhichKeyNormal", { bg = "#16161e" })
hl(0, "WhichKeySeparator", { fg = "#565f89" })
hl(0, "WhichKeyValue", { fg = "#737aa2" })
hl(0, "Whitespace", { fg = "#3b4261" })
hl(0, "WildMenu", { bg = "#283457" })
hl(0, "WinBar", { link = "StatusLine" })
hl(0, "WinBarNC", { link = "StatusLineNC" })
hl(0, "WinSeparator", { bold = true, fg = "#15161e" })
hl(0, "YankyPut", { link = "Search" })
hl(0, "YankyYanked", { link = "IncSearch" })
hl(0, "debugBreakpoint", { bg = "#192b38", fg = "#0db9d7" })
hl(0, "debugPC", { bg = "#16161e" })
hl(0, "diffAdded", { bg = "#243e4a", fg = "#449dab" })
hl(0, "diffChanged", { bg = "#1f2231", fg = "#6183bb" })
hl(0, "diffFile", { fg = "#7aa2f7" })
hl(0, "diffIndexLine", { fg = "#bb9af7" })
hl(0, "diffLine", { fg = "#565f89" })
hl(0, "diffNewFile", { bg = "#243e4a", fg = "#2ac3de" })
hl(0, "diffOldFile", { bg = "#4a272f", fg = "#2ac3de" })
hl(0, "diffRemoved", { bg = "#4a272f", fg = "#914c54" })
hl(0, "dosIniLabel", { link = "@property" })
hl(0, "healthError", { fg = "#db4b4b" })
hl(0, "healthSuccess", { fg = "#73daca" })
hl(0, "healthWarning", { fg = "#e0af68" })
hl(0, "helpCommand", { bg = "#414868", fg = "#7aa2f7" })
hl(0, "helpExample", { fg = "#565f89" })
hl(0, "htmlH1", { bold = true, fg = "#bb9af7" })
hl(0, "htmlH2", { bold = true, fg = "#7aa2f7" })
hl(0, "illuminatedCurWord", { bg = "#3b4261" })
hl(0, "illuminatedWord", { bg = "#3b4261" })
hl(0, "lCursor", { bg = "#c0caf5", fg = "#1a1b26" })
hl(0, "qfFileName", { fg = "#7aa2f7" })
hl(0, "qfLineNr", { fg = "#737aa2" })

vim.g.terminal_color_0 = '#15161e'
vim.g.terminal_color_8 = '#414868'
vim.g.terminal_color_1 = '#f7768e'
vim.g.terminal_color_9 = '#ff899d'
vim.g.terminal_color_2 = '#9ece6a'
vim.g.terminal_color_10 = '#9fe044'
vim.g.terminal_color_3 = '#e0af68'
vim.g.terminal_color_11 = '#faba4a'
vim.g.terminal_color_4 = '#7aa2f7'
vim.g.terminal_color_12 = '#8db0ff'
vim.g.terminal_color_5 = '#bb9af7'
vim.g.terminal_color_13 = '#c7a9ff'
vim.g.terminal_color_6 = '#7dcfff'
vim.g.terminal_color_14 = '#a4daff'
vim.g.terminal_color_7 = '#a9b1d6'
vim.g.terminal_color_15 = '#c0caf5'
